<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : English (American)
// Author of the language pack : MyBB Group
// Language pack translators website : http://www.mybb.com/
// Compatible version of MyBB : 1806
// Last edited in MyBB Editor by : ABeard
// Last edited date : Sun, 29 Nov 2015 17:31:10 +0000
// --------------------------------------------------------------------------------

$l['dvz_sb_shoutbox'] = 'Shoutbox';
$l['dvz_sb_archive'] = 'Shoutbox archive';
$l['dvz_sb_archivelink'] = 'Archive';
$l['dvz_sb_default'] = 'Enter your message...';
$l['dvz_sb_user_blocked'] = 'You have a shoutbox ban and cannot shout.';
$l['dvz_sb_minposts'] = 'Post at least {MINPOSTS} forum posts before you can enter our shoutbox.';
$l['dvz_sb_mod'] = 'Shoutbox moderation';
$l['dvz_sb_mod_banlist'] = 'Banned user ID\'s (comma seperated)';
$l['dvz_sb_mod_banlist_button'] = 'Save';
$l['dvz_sb_mod_clear'] = 'Delete messages older than...';
$l['dvz_sb_mod_clear_all'] = 'Delete all';
$l['dvz_sb_mod_clear_button'] = 'Delete';
$l['dvz_sb_delete_confirm'] = 'Do you really want to delete this shout?';
$l['dvz_sb_antiflood'] = 'Wait {ANTIFLOOD} seconds before shouting again.';
$l['dvz_sb_permissions'] = 'You cannot perform this action.';
$l['dvz_sb_away'] = 'You are currently away';
