<?php
/**
 * MyBB 1.8 English Language Pack
 * Copyright 2014 MyBB Group, All Rights Reserved
 *
 */

$l['delete_poll'] = 'Удалить опрос';
$l['close_thread'] = 'Закрыть тему';
$l['stick_thread'] = 'Прикрепить тему';

$l['author'] = 'Автор';
$l['message'] = 'Сообщение';
$l['threaded'] = 'Каскадный режим';
$l['linear'] = 'Линейный режим';
$l['thread_modes'] = 'Режимы темы';
$l['next_oldest'] = 'Предыдущая';
$l['next_newest'] = 'Следующая';
$l['view_printable'] = 'Версия для просмотра';
$l['send_thread'] = 'Отправить тему другу';
$l['subscribe_thread'] = 'Подписаться на тему';
$l['unsubscribe_thread'] = 'Отменить подписку на тему';
$l['add_poll_to_thread'] = 'Добавить опрос к этой теме';
$l['moderation_options'] = 'Модерирование темы:';
$l['delayed_moderation'] = 'Отложенная модерация';
$l['thread_notes'] = 'Редактировать / Просмотреть заметки темы';
$l['open_close_thread'] = 'Открыть / Закрыть тему';
$l['approve_thread'] = 'Подтвердить тему';
$l['unapprove_thread'] = 'Отклонить тему';
$l['soft_delete_thread'] = 'Мягко удалить тему';
$l['restore_thread'] = 'Восстановить тему';
$l['delete_thread'] = 'Удалить тему';
$l['delete_posts'] = 'Удалить выбранные сообщения';
$l['move_thread'] = 'Переместить / Скопировать тему';
$l['stick_unstick_thread'] = 'Прикрепить / Открепить тему';
$l['split_thread'] = 'Выделить сообщения в новую тему';
$l['merge_threads'] = 'Объединить темы';
$l['remove_redirects'] = 'Удалить ссылки';
$l['remove_subscriptions'] = 'Удалить все подписки';
$l['poll'] = 'Опрос:';
$l['show_results'] = 'Показать результаты';
$l['edit_poll'] = 'Редактировать опрос';
$l['public_note'] = '<b>Внимание!</b> Это открытый опрос, участникам предоставляется возможность видеть ответы других участников.';
$l['total'] = 'Всего';
$l['vote'] = 'Голосовать';
$l['total_votes'] = 'Голосов: {1}';
$l['you_voted'] = '* Вы проголосовали за этот ответ.';
$l['poll_closed'] = 'Опрос закрыт.';
$l['poll_closes'] = 'Этот опрос будет закрыт: {1}';
$l['already_voted'] = 'Вы уже проголосовали в этом опросе.';
$l['undo_vote'] = 'Отменить голос';
$l['quick_reply'] = 'Быстрый ответ';
$l['message_note'] = 'Введите текст Вашего сообщения.';
$l['signature'] = 'Подпись';
$l['email_notify'] = 'Уведомление';
$l['disable_smilies'] = 'Отключить смайлики';
$l['post_reply'] = 'Создать ответ';
$l['post_reply_img'] = 'Создать ответ';
$l['new_reply'] = 'Новый ответ';
$l['search_button'] = 'Поиск';
$l['post_thread'] = 'Создать тему';
$l['preview_post'] = 'Предварительный просмотр';
$l['rating_average'] = 'Голосов: {1} - Средняя оценка: {2}';
$l['rate_thread'] = 'Оценить эту тему:';
$l['thread_rating'] = 'Рейтинг темы:';
$l['similar_threads'] = 'Похожие темы';
$l['thread'] = 'Тема:';
$l['replies'] = 'Ответов:';
$l['views'] = 'Просмотров:';
$l['lastpost'] = 'Посл. сообщение';
$l['messages_in_thread'] = 'Сообщения в этой теме';
$l['users_browsing_thread'] = 'Пользователи просматривают эту тему:';
$l['users_browsing_thread_guests'] = '{1} Гость(ей)';
$l['users_browsing_thread_invis'] = '{1} Невидимый пользователь(и)';
$l['users_browsing_thread_reading'] = 'Читают...';
$l['inline_soft_delete_posts'] = 'Мягко удалить сообщения';
$l['inline_restore_posts'] = 'Восстановить сообщение';
$l['inline_delete_posts'] = 'Удалить сообщения';
$l['inline_merge_posts'] = 'Объединить сообщения';
$l['inline_split_posts'] = 'Переместить сообщение в другую тему';
$l['inline_move_posts'] = 'Переместить сообщение';
$l['inline_approve_posts'] = 'Одобрить сообщения';
$l['inline_unapprove_posts'] = 'Отклонить сообщения';
$l['inline_post_moderation'] = 'Модерирование сообщения:';
$l['inline_go'] = 'Выполнить';
$l['clear'] = 'Очистить выбранное';
$l['thread_closed'] = 'Тема закрыта';
$l['no_subject'] = 'без темы';
$l['error_nonextnewest'] = 'Со времени последнего просмотра Вами форума не появилось новых непрочитанных тем.';
$l['error_nonextoldest'] = 'Со времени последнего просмотра Вами форума нет более старых непрочитанных тем.';
$l['quickreply_multiquote_selected'] = 'Вы выделили одно или более сообщений для цитирования.';
$l['quickreply_multiquote_now'] = 'Цитировать эти сообщения сейчас';
$l['or'] = 'или';
$l['quickreply_multiquote_deselect'] = 'снять выделение';
$l['search_thread'] = 'Поиск по теме';
$l['enter_keywords'] = 'Ключевые слова';
$l['view_thread_notes'] = 'Заметки к теме';
$l['view_all_notes'] = 'Посмотреть все заметки';

$l['save_changes'] = 'Сохранить изменения';
$l['cancel_edit'] = 'Прервать редактирование';
$l['quick_edit_update_error'] = 'Произошла ошибка при редактировании Вашего ответа:';
$l['quick_reply_post_error'] = 'произошла ошибка при отправке Вашего ответа:';
$l['quick_delete_error'] = 'Произошла ошибка при удалении Вашего ответа:';
$l['quick_delete_success'] = 'Сообщение успешно удалено.';
$l['quick_delete_thread_success'] = 'Тема была успешно удалена.';
$l['quick_restore_error'] = 'Произошла ошибка при восстановлении Вашего ответа:';
$l['quick_restore_success'] = 'Сообщение успешно восстановлено.';

