<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:08:48 +0000
// --------------------------------------------------------------------------------

$l['nav_announcements'] = 'Объявление форума';
$l['announcements'] = 'Объявления';
$l['forum_announcement'] = 'Объявление форума: {1}';
$l['error_invalidannouncement'] = 'Объявление является недопустимым.';
$l['announcement_edit'] = 'Редактировать это объявление';
$l['announcement_qdelete'] = 'Удалить это объявление';
$l['announcement_quickdelete_confirm'] = 'Вы уверены, что хотите удалить это объявление?';
