<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:10:04 +0000
// --------------------------------------------------------------------------------

$l['archive_fullversion'] = 'Полная версия:';
$l['archive_replies'] = 'Ответов';
$l['archive_reply'] = 'Ответ';
$l['archive_pages'] = 'Страницы:';
$l['archive_note'] = 'Вы просматриваете упрощённую версию нашего контента. <a href="{1}">Просмотр полной версии</a> с полным форматированием.';
$l['archive_nopermission'] = 'К сожалению, у вас нет прав доступа к этому ресурсу.';
$l['error_nothreads'] = 'В настоящее время нет тем в этом форуме.';
$l['error_nopermission'] = 'У вас нет прав для просмотра темы в этом форуме.';
$l['error_unapproved_thread'] = 'Эта тема не утверждена. Пожалуйста, <a href="{1}">просмотрите полную версию</a> чтобы просмотреть содержимое этой темы.';
$l['archive_not_found'] = 'Запрашиваемая страница не найдена на этом сервере.';
$l['error_mustlogin'] = 'Эта доска объявлений требует входа от всех пользователей.';
