<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:10:31 +0000
// --------------------------------------------------------------------------------

$l['contact'] = 'Контактная информация';
$l['contact_no_message'] = 'Вы не указали сообщение для отправки.';
$l['contact_no_subject'] = 'Вы должны ввести тему сообщения.';
$l['contact_no_email'] = 'Вы должны ввести правильный адрес email.';
$l['contact_success_message'] = 'Ваше сообщение было успешно отправлено администратору.';
$l['contact_subject'] = 'Заголовок темы';
$l['contact_subject_desc'] = 'Кратко о теме вашего сообщения .';
$l['contact_message'] = 'Сообщение';
$l['contact_message_desc'] = 'Опишите подробно свое беспокойство .';
$l['contact_email'] = 'Email';
$l['contact_email_desc'] = 'Введите ваш адрес электронной почты, чтобы мы могли связаться с Вами.';
$l['contact_send'] = 'Отправить';
$l['subject_too_long'] = 'Заголовок слишком длинный. Пожалуйста введите заголовок короче чем {1} символов (текущее {2}).';
$l['message_too_short'] = 'Сообщение слишком короткое. Пожалуйста введите сообщение длиннее чем {1} символов (текущее {2})';
$l['message_too_long'] = 'Сообщение слишком длинное. Пожалуйста введите сообщение короче чем {1} символов (текущее {2})';
$l['error_stop_forum_spam_spammer'] = 'Извините, {1} совпадает с известным спамером и по этому Ваши контактные данные были заблокированы.';
$l['error_stop_forum_spam_fetching'] = 'Извините, ваше сообщение не прошло проверку на спам. Скорее всего, база данных не доступна. Пожалуйста, попробуйте снова позднее.';
