<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:11:52 +0000
// --------------------------------------------------------------------------------

$l['warnings_reached_max_warnings_day'] = 'Вы не можете предупредить кого-либо, как вы достигли лимита на количество предупреждений выдаваемых в день. <br /> <br /> Вы можете выдавать  максимальное количество предупреждени в день {1}. "';
$l['warnings_error_invalid_user'] = 'Выбранный пользователь не существует.';
$l['warnings_error_invalid_post'] = 'Выбранное сообщение не существует.';
$l['warnings_error_cannot_warn_self'] = 'Вы не можете добавить свой уровень предупреждений';
$l['warnings_error_user_reached_max_warning'] = 'Этот пользователь не может быть предупрежден, т.к. уже достиг максимального уровня предупреждения.';
$l['warnings_error_no_note'] = 'Вы не ввели никаких административных заметок для этого предупреждения.';
$l['warnings_error_invalid_type'] = 'Вы выбрали неверный тип предупреждения.';
$l['warnings_error_cant_custom_warn'] = 'У вас нет разрешения давать пользовательские предупреждения пользователям.';
$l['warnings_error_no_custom_reason'] = 'Вы не ввели причину для пользовательского предупреждения.';
$l['warnings_error_invalid_custom_points'] = 'Вы не ввели допустимое число очков предупреждения, чтобы добавить этому уровню пользователей. Вам необходимо ввести числовое значение больше 0, но, не более {1}.';
$l['warnings_error_invalid_expires_period'] = 'Вы ввели неверное время истечения срока действия.';
