<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:11:38 +0000
// --------------------------------------------------------------------------------

$l['pmdata_too_long_subject'] = 'Тема вашего личного сообщения слишком длинная. Пожалуйста, введите более короткий вариант.';
$l['pmdata_code_no_subject'] = '[без темы]';
$l['pmdata_missing_subject'] = 'Вы не ввели тему сообщения. Пожалуйста, введите тему.';
$l['pmdata_missing_message'] = 'Вы не ввели сообщение для отправки. Пожалуйста, введите сообщение.';
$l['pmdata_invalid_recipients'] = 'Один или несколько получателей, которые вы указали, не являются зарегистрированными участниками. Недействительные получатели: {1}';
$l['pmdata_no_recipients'] = 'Вы не ввели никаких получателей, чтобы отправить это сообщение. Вы должны ввести хотя бы одно имя пользователя в поле \'Кому\' .';
$l['pmdata_too_many_recipients'] = 'Вам разрешено отправлять сообщения только {1} пользователю(-ям) одновременно.';
$l['pmdata_recipient_is_ignoring'] = 'Вы не можете отправлять сообщения {1}, потому что они у вас в списке список игнорируемых.';
$l['pmdata_recipient_has_buddy_only'] = 'Вы не можете отправлять сообщения {1}, потому что вы не внесли их в спискок друзей.';
$l['pmdata_recipient_pms_disabled'] = '{1} отключил получение личных сообщений. Вы не можете отправлять личные сообщения этому пользователю.';
$l['pmdata_recipient_reached_quota'] = '{1} достиг лимита квоты личных сообщений, поэтому ваше сообщение не может быть отправлено.';
$l['pmdata_pm_flooding'] = 'Вы пытаетесь отправить сообщение слишком быстро после отправки предыдущего сообщения. Пожалуйста, подождите больше  {1} секунд.';
$l['pmdata_pm_flooding_one_second'] = 'Вы пытаетесь отправить сообщение слишком быстро после отправки предыдущего сообщения. Пожалуйста, подождите еще 1 секунду.';
