<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:11:28 +0000
// --------------------------------------------------------------------------------

$l['logindata_invalidpwordusername'] = 'Вы ввели не правильную компбинацию имя/пароль.<br /><br />Если Вы забыли своой пароль, пожалуйста<a href="member.php?action=lostpw">запросите новый</a>.';
$l['logindata_invalidpwordusernameemail'] = 'Вы ввели не правильную компбинацию email/пароль.<br /><br />Если Вы забыли своой пароль, пожалуйста<a href="member.php?action=lostpw">запросите новый</a>.';
$l['logindata_invalidpwordusernamecombo'] = 'Вы ввели не правильную компбинацию username/пароль или email/пароль. <br /><br />Если Вы забыли своой пароль, пожалуйста<a href="member.php?action=lostpw">запросите новый</a>.';
$l['logindata_regimageinvalid'] = 'Графический код проверки введен неправильно. Пожалуйста, введите его именно так, как он показан на изображении.';
$l['logindata_regimagerequired'] = 'Пожалуйста, заполните код проверки изображения, чтобы продолжить процесс входа в систему. Пожалуйста, введите его именно так, как он показан на изображении.';
