<?php
/**
 * MyBB 1.8 English Language Pack
 * Copyright 2014 MyBB Group, All Rights Reserved
 *
 */

$l['post_thread'] = 'Создать тему';
$l['moderated_by'] = 'Модераторы:';
$l['nothreads'] = 'Сожелеем, но в данном форуме нет тем для данной выборки по дате и времени.';
$l['search_forum'] = 'Поиск в форуме:';
$l['thread'] = 'Тема';
$l['author'] = 'Автор';
$l['replies'] = 'Ответов';
$l['views'] = 'Просмотров';
$l['lastpost'] = 'Последнее сообщение';
$l['rating'] = 'Рейтинг';
$l['prefix'] = 'Префикс:';
$l['prefix_all'] = 'Перфикс: Любой/Без префикса';
$l['prefix_any'] = "Префикс: Любой";
$l['prefix_none'] = "Префикс: Без префикса";
$l['markforum_read'] = 'Отметить этот форум прочитанным';
$l['subscribe_forum'] = 'Подписаться на этот форум';
$l['unsubscribe_forum'] = 'Отменить подписку на этот форум';
$l['clear_stored_password'] = 'Очистить сохраненный пароль форума';
$l['sort_by_subject'] = 'Сортировка по: заголовку';
$l['sort_by_lastpost'] = 'Сортировка по: посл.сообщению';
$l['sort_by_starter'] = 'Сортировка по: автору';
$l['sort_by_started'] = 'Сортировка по: времени создания';
$l['sort_by_rating'] = 'Сортировка по: рейтингу';
$l['sort_by_replies'] = 'Сортировка по: кол-ву ответов';
$l['sort_by_views'] = 'Сортировка по: кол-ву просмотров';
$l['sort_order_asc'] = 'Порядок: возрастание';
$l['sort_order_desc'] = 'Порядок: убывание';
$l['datelimit_1day'] = 'за сегодня';
$l['datelimit_5days'] = 'за 5 дней';
$l['datelimit_10days'] = 'за 10 дней';
$l['datelimit_20days'] = 'за 20 дней';
$l['datelimit_50days'] = 'за 50 дней';
$l['datelimit_75days'] = 'за 75 дней';
$l['datelimit_100days'] = 'за 100 дней';
$l['datelimit_lastyear'] = 'за год';
$l['datelimit_beginning'] = 'с начала';
$l['new_thread'] = 'Новые сообщения';
$l['new_hot_thread'] = 'Популярная тема (Новые сообщения)';
$l['posts_by_you'] = 'Содержит Ваши сообщения';
$l['no_new_thread'] = 'Нет новых сообщений';
$l['hot_thread'] = 'Популярная тема (Нет новых сообщений)';
$l['locked_thread'] = 'Закрытая тема';
$l['goto_first_unread'] = 'Перейти к первому непрочитанному сообщению';
$l['pages'] = 'Страницы:';
$l['pages_last'] = 'последняя';
$l['users_browsing_forum'] = 'Пользователи, просматривающие этот форум:';
$l['users_browsing_forum_guests'] = 'Гостей: {1}';
$l['users_browsing_forum_invis'] = 'Скрытых пользователей: {1}';
$l['delayed_moderation'] = 'Отложенная модерация';
$l['inline_thread_moderation'] = 'Модерирование темы:';
$l['close_threads'] = 'Закрыть темы';
$l['open_threads'] = 'Открыть темы';
$l['stick_threads'] = 'Прикрепить темы';
$l['unstick_threads'] = 'Открепить темы';
$l['soft_delete_threads'] = 'Мягкое удаление темы';
$l['restore_threads'] = 'Востановление темы';
$l['delete_threads'] = 'Удалить темы навсегда';
$l['move_threads'] = 'Переместить темы';
$l['approve_threads'] = 'Одобрить темы';
$l['unapprove_threads'] = 'Отклонить темы';
$l['inline_go'] = 'Выполнить';
$l['clear'] = 'Очистить';
$l['sub_forums_in'] = 'Форумы в \'{1}\'';
$l['forum_rules'] = '{1} - Правила';
$l['subforums'] = '<strong>Подфорумы:</strong>';
$l['asc'] = 'возр.';
$l['desc'] = 'убыв.';
$l['forum_announcements'] = 'Объявление форума';
$l['sticky_threads'] = 'Важные темы';
$l['normal_threads'] = 'Темы форума';
$l['icon_dot'] = 'Содержит Ваши сообщения. ';
$l['icon_no_new'] = 'Нет новых сообщений.';
$l['icon_new'] = 'Новые сообщения.';
$l['icon_hot'] = ' Популярная тема.';
$l['icon_lock'] = ' Тема закрыта.';
$l['attachment_count'] = 'Тема содержит 1 вложение.';
$l['attachment_count_multiple'] = 'Тема содержит {1} вложений.';
$l['rss_discovery_forum'] = 'Последние темы в {1}';
$l['forum_unapproved_posts_count'] = '{1} неодобренных сообщений в форуме.';
$l['forum_unapproved_post_count'] = '1 неодобренных сообщение в форуме.';
$l['forum_unapproved_threads_count'] = '{1} неодобренных тем в форуме.';
$l['forum_unapproved_thread_count'] = '1 неодобренных тема в форуме.';
$l['thread_unapproved_posts_count'] = '{1} неодобренных сообщений в теме.';
$l['thread_unapproved_post_count'] = '1 неодобренных сообщение в теме.';
$l['page_selected'] = 'Все <strong>{1}</strong> темы на этой странице выбраны.';
$l['all_selected'] = 'Все <strong>{1}</strong> темы в этом форуме выбраны.';
$l['select_all'] = 'Выбрать все <strong>{1}</strong> темы в этом форуме';
$l['clear_selection'] = 'Очистить выбранное';

$l['error_containsnoforums'] = 'Данный форум не содержит подфорумов.';

$l['inline_edit_description'] = '(Нажмите и удерживайте для редактирования)';
