<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:13:24 +0000
// --------------------------------------------------------------------------------

$l['hello'] = 'Hello World!';
$l['hello_add'] = 'Добавить';
$l['hello_add_message'] = 'Добавить сообщение';
$l['hello_empty'] = 'Сообщений не найдено.';
$l['hello_message_empty'] = 'Сообщение не может быть пустым.';
$l['hello_done'] = 'Новое сообщение успешно добавлено.';
