<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:13:33 +0000
// --------------------------------------------------------------------------------

$l['s1_name'] = 'Инструкции пользователю';
$l['s1_desc'] = 'Базовые инструкции пользователю для управления аккаунтом.';
$l['s2_name'] = 'Создание сообщений';
$l['s2_desc'] = 'Создание сообщений, ответы и базовое использование форума.';
