<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:13:42 +0000
// --------------------------------------------------------------------------------

$l['error_no_connection'] = 'Произошла ошибка при установке соединения с сервером:';
$l['error_no_message'] = 'Сообщение не указано.';
$l['error_no_subject'] = 'Заголовок не указан.';
$l['error_no_recipient'] = 'Не указано ни одного получателя.';
$l['error_not_sent'] = 'Ошибка при попытке отправить почту через PHP функцию mail .';
$l['error_status_missmatch'] = 'Статус с сервера не совпадает с ожидаемым результатом, возвращает:';
$l['error_data_not_sent'] = 'Эти данные не могут быть отправлены на сервер:';
$l['error_occurred'] = 'Произошла одна или несколько ошибок . Исправьте следующие ошибки, прежде чем продолжить. <br />';
