<?php
/***************************************************************************
 *
 *   Mods &amp; Downloads plugin (/inc/languages/english/mydownloads.php)
 *	 Author: Diogo Parrinha
 *   Copyright: © 2009-2010 Diogo Parrinha
 *   
 *   !!!!!!!!!!!TRANSLATION IS NOT READY YET!!!!!!!!!!!          95% done
 *
 *   Website: http://www.mybb-plugins.com
 *
 *   Mods &amp; Downloads adds a downloads system to MyBB.
 *
 ***************************************************************************/
 
/****************************************************************************
* You are NOT authorized to share/re-distribute this plugin with ANYONE without my express permission.
* You MUST NOT give credits to anyone besides me, Diogo Parrinha.
* You MUST NOT remove the license file or any conditions/rules that you may find in the included PHP files.
* The author is NOT responsible for any damaged caused by this plugin.
* 
* By downloading/installing this module you agree with the conditions stated above.
****************************************************************************/

$l['mydownloads_filetype'] = "Тип файла:";
$l['mydownloads_status_type'] = "<strong>Статус:</strong>";
$l['mydownloads_active'] = 'Публичный';
$l['mydownloads_suspended'] = "<font color=\"red\">Заблокирован</font>";
$l['mydownloads_download_is_suspended'] = "Этот файл был заблокирован, и теперь доступ к нему имеют только автор и администрация сайта. ";
$l['mydownloads_suspended2'] = "<font color=\"red\"(Заблокирован)</font>";
$l['mydownloads_return'] = "Вернуться";
$l['myalerts_setting_mydownloads_new_comment'] = 'Получать уведомление, когда кто-либо комментирует загруженный вами файл?';
$l['mydownloads'] = 'Моды &amp; Загрузки';
$l['mydownloads_add'] = 'Добавить';
$l['mydownloads_add_previews'] = 'Добавить изображения';
$l['mydownloads_add_previews_desc'] = 'Для загрузки изображения, перетащите его в поле ниже.';
$l['mydownloads_all_categories'] = 'Все категории';
$l['mydownloads_already_rated'] = "Вы уже оценили эту загрузку.";
$l['mydownloads_asc'] = 'восх';
$l['mydownloads_being_updated'] = 'Обновляется';
$l['mydownloads_being_updated2'] = "(Обновляется)";
$l['mydownloads_being_updated_error'] = 'Эта загрузка была обновлена. Вы не можете изменять её, покуда она находится на рассмотрении.';
$l['mydownloads_being_updated_notice'] = 'Эта загрузка была обновлена, и в данный момент она ожидает рассмотрения. Тем временем, вы можете скачать старую версию.';
$l['mydownloads_by_user'] = '';
$l['mydownloads_by_username'] = 'от <a href="{1}/{2}">{3}</a>';
$l['mydownloads_cancel'] = 'Отмена';
$l['mydownloads_cancel_upload'] = 'Отменить загрузку';
$l['mydownloads_cannot_rate_own'] = 'Вы не можете оценивать собственные загрузки.';
$l['mydownloads_cant_edit_comment'] = 'Вы не можете изменить комментарий, так как время на изменение закончилось.';
$l['mydownloads_categories'] = "Категории";
$l['mydownloads_categories_main'] = 'Главная страница';
$l['mydownloads_category'] = 'Категория';
$l['mydownloads_closed'] = "Страница загрузок временно закрыта.";
$l['mydownloads_collaborating'] = 'Мои совместные работы';
$l['mydownloads_collaborators'] = 'Соавторы';
$l['mydownloads_collaborators_updated'] = 'Список соавторов обновлен.';
$l['mydownloads_collaborator_username'] = 'Имя пользователя';
$l['mydownloads_comment'] = "Оставить комментарий";
$l['mydownloads_comment_banned'] = "Вы заблокированы и не можете оставлять комментарии.";
$l['mydownloads_confirm_delete'] = 'Подтвердите удаление выбранного комментария.<br /><form action="{1}/mydownloads/comment_download.php" method="post" "><input type="hidden" name="my_post_key" value="{2}" /><input type="hidden" name="cid" value="{3}" /><input type="hidden" name="action" value="delete_comment" /><input type="submit" value="Delete" class="button" /></form>';
$l['mydownloads_cover'] = 'Обложка';
$l['mydownloads_cover_updated'] = 'Обложка обновлена.';
$l['mydownloads_date'] = 'Дата';
$l['mydownloads_default_license'] = "Автор не установил лицензию на эти файлы.";
$l['mydownloads_delete'] = 'Удалить';
$l['mydownloads_delete_confirm'] = "Вы уверены, что хотите удалить данный комментарий?";
$l['mydownloads_delete_download'] = 'Удалить загруженные файлы';
$l['mydownloads_delete_download_breadcrumb'] = 'Удаляем файлы';
$l['mydownloads_delete_download_confirm'] = 'Вы уверены, что хотите удалить "{1}"?';
$l['mydownloads_delete_preview_confirm'] = 'Вы уверены, что хотите удалить выбранное изображение?';
$l['mydownloads_desc'] = 'описание';
$l['mydownloads_download'] = "Скачать";
$l['mydownloads_downloaded'] = "<strong>Файлы:</strong> {1}";
$l['mydownloads_downloads'] = 'Загрузки';
$l['mydownloads_downloads_number'] = "{1} файлы";
$l['mydownloads_download_category'] = 'Категория';
$l['mydownloads_download_changelog'] = 'Cписок изменений';
$l['mydownloads_download_collaborator'] = 'Соавтор';
$l['mydownloads_download_commented'] = "Вы успешно оставили комментарий.";
$l['mydownloads_download_commented_title'] = "Комментарий оставлен";
$l['mydownloads_download_comments'] = "Комментарии";
$l['mydownloads_download_comment_deleted'] = "Вы успешно удалили комментарий.";
$l['mydownloads_download_comment_deleted_title'] = "Комментарий удален";
$l['mydownloads_download_comment_edited'] = 'Комментарий изменен.';
$l['mydownloads_download_deleted'] = 'Вы удалили выбранный файл.';
$l['mydownloads_download_deleted_title'] = 'Файл удален';
$l['mydownloads_download_delete_comment'] = "Удалить";
$l['mydownloads_download_description'] = "Описание";
$l['mydownloads_download_edit_comment'] = "Изменить";
$l['mydownloads_download_image'] = "Скачать картинку";
$l['mydownloads_download_invited'] = 'Приглашен';
$l['mydownloads_download_name'] = "Имя";
$l['mydownloads_download_points'] = "Очки";
$l['mydownloads_download_preview'] = "Изображение";
$l['mydownloads_download_price'] = "Цена";
$l['mydownloads_download_purchased'] = "Вы успешно приобрели этот файл/файлы.";
$l['mydownloads_download_purchased_title'] = "Файлы куплены";
$l['mydownloads_download_rate'] = "Рейтинг";
$l['mydownloads_download_rated'] = "Вы успешно оценили загрузку.";
$l['mydownloads_download_rated_title'] = "Загрузка оценена";
$l['mydownloads_download_submitter'] = 'Заявитель';
$l['mydownloads_download_successfully_added'] = "Вы успешно добавили файлы, теперь они проходят модерацию.";
$l['mydownloads_download_successfully_added_auto'] = "Вы успешно добавили файлы, они автоматически одобрены системой модерации.";
$l['mydownloads_download_successfully_added_title'] = 'Файлы загружены';
$l['mydownloads_download_successfully_added_title_auto'] = 'Файлы загружены и прошли проверку';
$l['mydownloads_download_successfully_edited'] = "Вы успешно изменили файлы, теперь они проходят модерацию.";
$l['mydownloads_download_successfully_edited_auto'] = "Вы успешно изменили файлы, изменения автоматически одобрены системой модерации.";
$l['mydownloads_download_successfully_edited_title'] = 'Файл изменен';
$l['mydownloads_download_successfully_edited_title_auto'] = 'Файл изменен, подтверждение получено';
$l['mydownloads_download_url'] = 'Показать ссылку (ссылки) на скачивание';
$l['mydownloads_download_views'] = "Просмотры";
$l['mydownloads_edit'] = 'Изменить';
$l['mydownloads_editing_collaborators'] = 'Изменить список соавторов {1}';
$l['mydownloads_editing_download'] = 'Изменяем {1}';
$l['mydownloads_editing_invited'] = 'Изменение списка пользователей, приглашенных в {1}';
$l['mydownloads_edit_collaborators'] = 'Изменить список соавторов';
$l['mydownloads_edit_comment'] = "Изменить комментарий";
$l['mydownloads_edit_download'] = 'Изменить файл';
$l['mydownloads_edit_download_download_desc'] = 'Выберите файл для загрузки. (Оставьте поле пустым, если последнее не требуется)';
$l['mydownloads_edit_download_preview_desc'] = 'Выберите обложку для загрузки. (Оставьте поле пустым, если последнее не требуется)';
$l['mydownloads_edit_invited'] = 'Изменить список приглашенных пользователей';
$l['mydownloads_empty_reason'] = 'Вы должны указать причину жалобы.';
$l['mydownloads_enter_a_comment'] = 'Пожалуйста, введите комментарий.';
$l['mydownloads_error'] = 'Ошибка';
$l['mydownloads_error_attachsize'] = "Размер выбранного вами файла слишком велик. Максимально допустимый размер составляет {1} кб.";
$l['mydownloads_error_attachtype'] = "Файлы такого типа не поддерживаются. Выберите файлы с поддерживаемым типом.";
$l['mydownloads_error_invalidrating'] = "Вы выбрали недопустимую оценку.";
$l['mydownloads_error_uploadfailed'] = "Невозможно загрузить данный файл. Выберите другой и попробуйте еще раз. ";
$l['mydownloads_error_uploadfailed_detail'] = "Детали ошибки: ";
$l['mydownloads_error_uploadfailed_lost'] = "Невозможно найти прикрепленный файл.";
$l['mydownloads_error_uploadfailed_movefailed'] = "Возникла ошибка при перемещении файла.";
$l['mydownloads_error_uploadfailed_nothingtomove'] = "Был выбран неправильный файл, поэтому перемещение невозможно.";
$l['mydownloads_error_uploadfailed_php1'] = "PHP returned: Uploaded file exceeded upload_max_filesize directive in php.ini.  Please contact your forum administrator with this error.";
$l['mydownloads_error_uploadfailed_php2'] = "Размер загруженного файла превосходит допустимый размер.";
$l['mydownloads_error_uploadfailed_php3'] = "Файл был загружен лишь частично.";
$l['mydownloads_error_uploadfailed_php4'] = "Файл не был загружен.";
$l['mydownloads_error_uploadfailed_php6'] = "PHP returned: Missing a temporary folder.  Please contact your forum administrator with this error.";
$l['mydownloads_error_uploadfailed_php7'] = "PHP returned: Failed to write the file to disk.  Please contact your forum administrator with this error.";
$l['mydownloads_error_uploadfailed_phpx'] = "PHP returned error code: {1}.  Please contact your forum administrator with this error.";
$l['mydownloads_error_uploadsize'] = "Размер загружаемого файла слишком велик.";
$l['mydownloads_exceeded'] = 'Лимит загрузок превышен. Максимальный: {1}.';
$l['mydownloads_filter_by_tags'] = 'Фильтровать результаты по тегам:';
$l['mydownloads_five_stars'] = "5 звезд из 5";
$l['mydownloads_flood_check'] = "Вы оставляете комментарии слишком часто. Подождите еще {1} секунд."; // copied from MyBB :P
$l['mydownloads_forum'] = 'Форум';
$l['mydownloads_four_stars'] = "3 звезды из 5";
$l['mydownloads_go_to_all_downloads'] = 'Перейти в раздел "все загрузки"';
$l['mydownloads_guidelines'] = "Это руководства! BB Code is [b]allowed[/b].";
$l['mydownloads_header_reports'] = 'Есть {1} непрочитанных жалоб на файлы.';
$l['mydownloads_hidden'] = 'Скрытый';
$l['mydownloads_hidden2'] = '(Скрытый)';
$l['mydownloads_history'] = 'История скачиваний';
$l['mydownloads_history_visible'] = 'История скачиваний показана';
$l['mydownloads_history_visible_desc'] = 'Снимите галочку, если вы хотите отключить историю версий.';
$l['mydownloads_in'] = 'в';
$l['mydownloads_invalid_banner'] = 'Недопустимый баннер. Допустимы только следующие форматы: bmp, gif, png, jpeg.';
$l['mydownloads_invalid_extension'] = 'Изображение может быть только в следующих форматах: jpeg, png or gif.';
$l['mydownloads_invalid_points'] = 'Вы ввели неверное число очков.';
$l['mydownloads_invalid_receiver_email'] = 'Вы ввели неверный почтовый адрес.';
$l['mydownloads_invalid_url'] = 'Данная ссылка неверна: ';
$l['mydownloads_invalid_user'] = 'Вы выбрали неправильного пользователя.';
$l['mydownloads_invited'] = 'Доступ пользователей';
$l['mydownloads_invited_updated'] = 'Список приглашенных пользователей обновлен.';
$l['mydownloads_invited_username'] = 'Имя пользователя';
$l['mydownloads_invite_only'] = "Приглашать только";
$l['mydownloads_invite_only2'] = "(Приглашать только)";
$l['mydownloads_last_updated'] = 'Последнее обновление';
$l['mydownloads_latest_submissions'] = 'Последние добавленные';
$l['mydownloads_license'] = 'Лицензия';
$l['mydownloads_log_in_register'] = "Вы должны на сайт, чтобы комментировать.";
$l['mydownloads_manage_previews'] = 'Управление изображениями';
$l['mydownloads_max_height'] = 'Высота вашей картинки больше допустимого значения в {1}px.';
$l['mydownloads_max_previews'] = 'Вы можете добавить максимум {1} изображений к каждому файлу.';
$l['mydownloads_max_previews_error'] = 'Вы больше не можете добавлять изображения, так как вы превысили допустимый лимит.';
$l['mydownloads_max_res'] = 'Максимальные размеры изображения - {1}px в ширину и {2}px в высоту.';
$l['mydownloads_max_width'] = 'Ширина вашей картинки больше допустимого значения в {1}px.';
$l['mydownloads_md5'] = 'MD5';
$l['mydownloads_message'] = "Сообщение";
$l['mydownloads_most_downloaded'] = 'Самые скачиваемые';
$l['mydownloads_most_rated'] = 'С наивысшим рейтингом';
$l['mydownloads_most_viewed'] = 'По наибольшим числом просмотров';
$l['mydownloads_mysubmissions'] = 'Мои файлы';
$l['mydownloads_my_submissions'] = 'Мои загрузки <span class="smalltext">(показаны только файлы, прошедшие модерацию)</span>';
$l['mydownloads_my_submissions_collab'] = 'Мои совместные работы <span class="smalltext">(показаны только работы, прошедшие модерацию)</span>';
$l['mydownloads_my_submissions_profile'] = 'Загрузки:';
$l['mydownloads_na'] = "Неизвестно";
$l['mydownloads_new_comment'] = 'К вашиму файлу был оставлен комментарий {1}.';
$l['mydownloads_not_enough_money'] = "Недостаточно очков для покупки.";
$l['mydownloads_no_categories'] = "Категории не найдены.";
$l['mydownloads_no_cid'] = "Вы выбрали неверную категорию.";
$l['mydownloads_no_collaborations'] = 'Совместные работы не найдены.';
$l['mydownloads_no_comid'] = "Выбранный вами комментарий неверен.";
$l['mydownloads_no_description'] = "Вы не ввели описание.";
$l['mydownloads_no_did'] = "Выбранный вами файл не подходит.";
$l['mydownloads_no_dl_name'] = "Вы не ввели название.";
$l['mydownloads_no_dl_visibility'] = 'Вы неверно установили параметр видимости.';
$l['mydownloads_no_downloads'] = "Файлы не найдены.";
$l['mydownloads_no_download_file'] = "Вы не выбрали файл(ы) для загрузки.";
$l['mydownloads_no_hidden'] = "Вы не ввели параметр для 'скрыто'.";
$l['mydownloads_no_money'] = "Денег нет, но вы держитесь";
$l['mydownloads_no_permissions'] = "Либо у вас нет прав на просмотр этого файла, либо он скрыт администрацией.<br/>Если вы создатель данного файла, свяжитесь с админстрацией.";
$l['mydownloads_no_points_set'] = "Нет очков";
$l['mydownloads_no_previews'] = 'Нет изображений.';
$l['mydownloads_no_price_set'] = "Цена не указана";
$l['mydownloads_no_submissions'] = 'Файлы не найдены.';
$l['mydownloads_no_sub_categories'] = "Подкатегории не найдены.";
$l['mydownloads_no_version_set'] = 'Версия не указана.';
$l['mydownloads_number_downloads'] = "Загрузки";
$l['mydownloads_one_star'] = "1 звезда из 5";
$l['mydownloads_options'] = 'Опции';
$l['mydownloads_previews'] = 'Изображения';
$l['mydownloads_preview_deleted'] = 'Изображение успешно удалено.';
$l['mydownloads_preview_empty'] = 'Файл с изображением отсутствует.';
$l['mydownloads_preview_submitted'] = 'Изображение успешно отправлено.';
$l['mydownloads_processing'] = 'Выполняем...';
$l['mydownloads_public'] = "Общий<";
$l['mydownloads_purchase'] = "Купить файл, используя {1}";
$l['mydownloads_purchase_image'] = "Купить картинку, используя {1}";
$l['mydownloads_purchase_url'] = 'Купить ссылку (ссылки) на скачивание, используя {1}';
$l['mydownloads_rate_banned'] = "Вы заблокированы и не можете оценивать.";
$l['mydownloads_ratings_update_error'] = 'Невозможно оценить:';
$l['mydownloads_rating_too_fast'] = 'Вы можете оценивать только раз в {1} секунд. Попробуйте через {2} секунды.';
$l['mydownloads_remove'] = 'Удалить';
$l['mydownloads_remove_collaborator_confirm'] = 'Вы уверены что хотите убрать этого соавтора из списка?';
$l['mydownloads_remove_invited_confirm'] = 'Вы уверены что хотите убрать этого приглашенного пользователя из списка?';
$l['mydownloads_reported_message'] = 'Вы успешно отправили жалобу на файл.';
$l['mydownloads_reported_title'] = 'Жалоба отправлена';
$l['mydownloads_report_breacrumb'] = 'Отправляем жалобу ';
$l['mydownloads_report_download'] = 'Жалоба на файл';
$l['mydownloads_report_download_reason'] = 'Причина';
$l['mydownloads_report_download_reason_desc'] = 'Укажите причину, по которой вы отправляете жалобу.';
$l['mydownloads_require_preview'] = 'Необходима обложка.';
$l['mydownloads_search'] = 'Поиск файлов';
$l['mydownloads_search_results'] = 'Результаты поиска: ';
$l['mydownloads_select_category'] = 'Выберите категорию';
$l['mydownloads_set_banner'] = 'Установить баннер';
$l['mydownloads_set_cover'] = 'Установить обложку';
$l['mydownloads_sortby'] = 'Сортировать:';
$l['mydownloads_start'] = 'Начать';
$l['mydownloads_start_upload'] = 'Начать загрузку';
$l['mydownloads_stats'] = 'Статистика';
$l['mydownloads_stats_of'] = 'Статистика категории {1}';
$l['mydownloads_status'] = 'Статус';
$l['mydownloads_submissions'] = 'Загрузки';
$l['mydownloads_submit'] = 'Загрузить';
$l['mydownloads_submitter_desc'] = 'Пользователь загрузил файл.';
$l['mydownloads_submit_comment'] = "Загрузить";
$l['mydownloads_submit_date'] = 'Указать дату';
$l['mydownloads_submit_download'] = 'Загрузить файл';
$l['mydownloads_submit_download_bannerurl'] = 'Ссылка на баннер';
$l['mydownloads_submit_download_bannerurl_desc'] = 'Вы можете указать ссылку на баннер. Для лучшего отображения используйте как минимум разрешение 1500x300 или изображение похожего формата. Допустимые расширения: bmp, gif, png, jpeg.';
$l['mydownloads_submit_download_changelog'] = 'Список изменений';
$l['mydownloads_submit_download_changelog_desc'] = 'Укажите историю версий для вашего файла.';
$l['mydownloads_submit_download_description'] = 'Описание';
$l['mydownloads_submit_download_description_desc'] = 'Укажите описание для вашего файла.';
$l['mydownloads_submit_download_download'] = 'Скачать файл';
$l['mydownloads_submit_download_download_desc'] = 'Выберите файл для загрузки.';
$l['mydownloads_submit_download_email'] = 'PayPal Email';
$l['mydownloads_submit_download_email_desc'] = 'Укажите ваш почтовый ящик PayPal, на который будут приходить деньги. Оставьте пустым, если вы хотите чтобы деньги вместо вас получала администрация. Если вы заполните это поле но укажите цену равную нулю, то появится кнопка пожертвований.';
$l['mydownloads_submit_download_in_category'] = 'Определяем файл в категорию "{1}"';
$l['mydownloads_submit_download_license'] = 'Лицензия';
$l['mydownloads_submit_download_license_desc'] = 'Введите лицензию на данный файл, либо оставьте это поле пустым.';
$l['mydownloads_submit_download_name'] = 'Имя';
$l['mydownloads_submit_download_name_desc'] = 'Имя загрузки.';
$l['mydownloads_submit_download_points'] = 'Очки';
$l['mydownloads_submit_download_points_desc'] = 'Выберите цену этой загрузки в очках. Каждый раз когда ваш файл покупают за очки, вы будете получать количество очков умноженное на коэффициент, установленный администрацией.';
$l['mydownloads_submit_download_points_desc_mp_not_installed'] = '<span style="color: #FF0000;"><strong>NewPoints отключены. Оставьте пустым.</strong></span>';
$l['mydownloads_submit_download_preview'] = 'Обложка';
$l['mydownloads_submit_download_preview_desc'] = 'Выберите изображение-обложку. Оно будет показываться рядом с вашим файлом в списке загрузок.';
$l['mydownloads_submit_download_price'] = 'Цена';
$l['mydownloads_submit_download_price_desc'] = 'Укажите сколько пользователь должен заплатить с помощью PayPal для того, чтобы скачать файл';
$l['mydownloads_submit_download_price_desc_paypal_deactivated'] = '<span style="color: #FF0000;"><strong>PayPal недоступен. Оставьте это поле пустым.</strong></span>';
$l['mydownloads_submit_download_short_description'] = 'Короткое описание';
$l['mydownloads_submit_download_short_description_desc'] = 'Максимум - 150 символов. Введите короткое описние для данного файла.';
$l['mydownloads_edit_download_short_description_desc'] = 'Максимум - 150 символов. Введите короткое описние для данного файла.';
$l['mydownloads_submit_download_tags'] = 'Теги';
$l['mydownloads_submit_download_tags_desc'] = 'Выберите теги, по которым можно будет найти ваши файлы.';
$l['mydownloads_submit_download_urls'] = 'Ссылки на скачивание';
$l['mydownloads_submit_download_urls_desc'] = 'Это опциональное поле для ввода ссылок на скачивание файлов. Если вы всё же собираетесь загрузить файл непосредственно на ресурс, оставьте это поле в пустым. В противном случае файл не будет загружен.';
$l['mydownloads_submit_download_version'] = 'Версия';
$l['mydownloads_submit_download_version_desc'] = 'Укажите версию. Оставьте это поле пустым, если не собираетесь указывать.';
$l['mydownloads_submit_download_visibility'] = 'Видимость';
$l['mydownloads_submit_preview'] = 'Отправить изображение';
$l['mydownloads_sub_categories'] = 'Подкатегории';
$l['mydownloads_sub_categories2'] = '{1} Подкатегории и {2} файлы';
$l['mydownloads_sub_categories_in_cat'] = 'Категории, чья родительская категория - "{1}"';
$l['mydownloads_success'] = 'Успех';
$l['mydownloads_switch_dragdrop'] = 'Переключиться на режим перетаскивания';
$l['mydownloads_switch_legacy'] = 'Переключиться на альтернативную';
$l['mydownloads_tags'] = 'Теги';
$l['mydownloads_three_stars'] = "3 звезды из 5";
$l['mydownloads_total_rate'] = "Средний рейтинг";
$l['mydownloads_two_stars'] = "2 звезды из 5";
$l['mydownloads_unlisted'] = "Незарегистрированный<";
$l['mydownloads_unlisted2'] = "(Незарегистрированный)";
$l['mydownloads_suspended'] = "Приостановленный";
$l['mydownloads_upload_problem_dl_already_exists'] = "Файл с подобным именем уже существует";
$l['mydownloads_upload_problem_downloadfile'] = "При загрузке файла произошла следующая ошибка: ";
$l['mydownloads_upload_problem_previewfile'] = "При загрузке изображения произошла следующая ошибка: ";
$l['mydownloads_upload_problem_pr_already_exists'] = "Изображение с таким именем уже существует";
$l['mydownloads_url_download'] = "Создатель данного файла не загружал файл непосредственно на ресурс, но вы можете скачать файл по ссылкам.<br />Вот они:<br />{1}";
$l['mydownloads_url_download_title'] = "Скачать файл";
$l['mydownloads_user_history'] = '{1}\'s История скачиваний';
$l['mydownloads_user_mysubmissions'] = 'Файлы от {1}';
$l['mydownloads_user_submissions'] = 'Загрузки {1} <span class="smalltext">(only approved downloads are shown)</span>';
$l['mydownloads_use_legacy'] = 'Используйте альтернативную версию.';
$l['mydownloads_version'] = 'Версия';
$l['mydownloads_viewed'] = "<br /><strong>Просмотров:</strong> {1}";
$l['mydownloads_view_history'] = 'История скачиваний';
$l['mydownloads_view_submissions'] = 'Показать загрузки';
$l['mydownloads_your_money'] = "У вас есть";
$l['mydownloads_your_rate'] = "Ваш рейтинг";
?>