<?php
/**
 * MyBB 1.8 English Language Pack
 * Copyright 2014 MyBB Group, All Rights Reserved
 *
 */

$l['nav_online'] = 'Кто на форуме';
$l['nav_onlinetoday'] = 'Кто сегодня был на форуме';

$l['viewing_announcements'] = 'Просматривает объявления форума <a href="{1}">{2}</a>';
$l['viewing_announcements2'] = 'Просматривает объявления форума';
$l['viewing_attachment'] = 'Просматривает вложение';
$l['viewing_attachment2'] = 'Просматривает <a href="attachment.php?aid={1}">вложение</a> в теме <a href="{3}">{2}</a>';
$l['viewing_calendar'] = 'Просматривает <a href="calendar.php">Календарь</a>';
$l['viewing_event'] = 'Просматривает событие';
$l['viewing_event2'] = 'Просматривает событие <a href="{1}">{2}</a>';
$l['adding_event'] = '<a href="calendar.php?action=addevent">Добавляет событие</a>';
$l['editing_event'] = 'Редактирует событие';
$l['viewing_contact_us'] = 'Просмотр <a href="contact.php">обратная связь</a>';
$l['editing_post'] = 'Редактирует сообщение';
$l['viewing_forum'] = 'Просматривает форум';
$l['viewing_forum2'] = 'Просматривает форум <a href="{1}">{2}</a>';
$l['forum_redirect_to'] = 'Переходит к <a href="{1}">{2}</a>';
$l['viewing_index'] = '{1} <a href="index.php">На главной странице</a>';
$l['activating_account'] = 'Активирует учетную запись';
$l['viewing_profile'] = 'Просматривает профиль';
$l['viewing_profile2'] = 'Просматривает профиль <a href="{1}">{2}</a>';
$l['registering'] = '<a href="member.php?action=register">Регистрируется</a>';
$l['logging_in'] = '<a href="member.php?action=login">Входит</a>';
$l['logging_in_plain'] = 'Входит';
$l['logging_out'] = 'Выходит';
$l['emailing_user'] = 'Пишет e-mail письмо';
$l['rating_user'] = 'Оценивает пользователя';
$l['viewing_memberlist'] = 'Просматривает <a href="memberlist.php">список пользователей</a>';
$l['viewing_whoposted'] = 'Просматривает авторов';
$l['viewing_whoposted2'] = 'Просматривает авторов сообщений в теме <a href="showthread.php?tid={1}">{2}</a>';
$l['marking_read'] = '<a href="misc.php?action=markread&amp;my_post_key={1}">Отмечает форумы прочитанными</a>';
$l['viewing_helpdocs'] = 'Просматривает <a href="misc.php?action=help">справку</a>';
$l['viewing_buddylist'] = 'Просматривает <a href="misc.php?action=buddypopup">список друзей</a>';
$l['viewing_smilies'] = 'Просматривает <a href="misc.php?action=smilies">список смайликов</a>';
$l['viewing_syndication'] = 'Просматривает <a href="misc.php?action=syndication">список RSS</a>';
$l['replying_thread'] = 'Отвечает в теме';
$l['replying_thread2'] = 'Отвечает в теме <a href="{1}">{2}</a>';
$l['posting_thread'] = 'Создает новую тему';
$l['posting_thread2'] = 'Создает новую тему в <a href="{1}">{2}</a>';
$l['viewing_wol'] = 'Просматривает <a href="online.php">Список онлайн</a>';
$l['viewing_woltoday'] = 'Просматривает, <a href="online.php?action=today">кто сегодня был на форуме</a>';
$l['creating_poll'] = 'Создает опрос';
$l['editing_poll'] = 'Редактирует опрос';
$l['viewing_pollresults'] = 'Просматривает результаты голосования';
$l['voting_poll'] = 'Голосует в опросе';
$l['using_modtools'] = 'Модерирует';
$l['sending_pm'] = 'Отправляет личное сообщение';
$l['reading_pm'] = 'Читает личное сообщение';
$l['editing_pmfolders'] = 'Настраивает папки личных сообщений';
$l['using_pmsystem'] = 'Использует систему личных сообщений';
$l['reporting_post'] = 'Отправляет отчет о сообщении';
$l['searching_forum'] = '<a href="search.php">Пользуется поиском</a>{1}';
$l['reading_thread'] = 'Читает тему';
$l['reading_thread2'] = 'Читает тему <a href="{1}">{2}</a> {3}';
$l['viewing_team'] = 'Просматривает список администрации';
$l['viewing_stats'] = 'Просматривает статистику форума';
$l['updating_profile'] = '<a href="usercp.php?action=profile">Редактирует профиль</a>';
$l['updating_options'] = '<a href="usercp.php?action=options">Редактирует настройки</a>';
$l['editing_signature'] = '<a href="usercp.php?action=editsig">Редактирует подпись</a>';
$l['changing_avatar'] = '<a href="usercp.php?action=avatar">Меняет аватар</a>';
$l['viewing_subscriptions'] = 'Просматривает <a href="usercp.php?action=subscriptions">подписки на темы</a>';
$l['editing_pad'] = 'Редактирует <a href="usercp.php?action=notepad">дневник</a>';
$l['editing_password'] = 'Редактирует <a href="usercp.php?action=password">пароль</a>';
$l['user_cp'] = 'В <a href="usercp.php">панели управления</a>';
$l['viewing_portal'] = 'Просматривает <a href="portal.php">страницу портала</a>';
$l['viewing_noperms'] = 'Просматривает страницу без прав доступа';
$l['unknown_location'] = '<a href="{1}">Неизвестное действие</a>';
$l['giving_reputation'] = 'Изменяет рейтинг на <a href="{1}">{2}</a>';
$l['viewing_reputation_report'] = 'Просмотривае рейтинг <a href="{1}">{2}</a>';
$l['viewing_reputation_report2'] = 'Просмотривает рейтинг';
$l['member_resendactivation'] = 'Повторяет отправку активационного письма';
$l['member_lostpw'] = 'Получает <a href="member.php?action=lostpw">забытый пароль</a>';
$l['sending_thread'] = 'Отправляет тему другу';
$l['guest'] = 'Гость';
$l['page'] = 'Страница';
$l['users_online'] = 'Кто на форуме';
$l['on_username'] = 'Пользователь';
$l['time'] = 'Время';
$l['location'] = 'Место';
$l['online_today'] = 'Кто сегодня был на форуме';
$l['refresh_page'] = 'Обновить';
$l['online_online_plural'] = 'пользователя';
$l['online_online_singular'] = 'пользователь';
$l['online_member_plural'] = 'пользователей';
$l['online_member_singular'] = 'пользователь';
$l['online_anon_plural'] = '&#10;';
$l['online_anon_singular'] = '&#10;';
$l['online_guest_plural'] = 'гости';
$l['online_guest_singular'] = 'гость';
$l['online_count'] = '{1} {2} Пользователей за последние {3} минут: ({4} {5}, невидимых {6} из {7}, и {8}{9}).';
$l['ip'] = 'IP:';
$l['resolves_to'] = 'Имя хоста:';
$l['if_resolvable'] = '(если определяется)';
$l['admin_options'] = 'Опции администратора:';
$l['search_regip_users'] = 'Поиск пользователей, зарегистрировавшихся с этого IP-адреса';
$l['search_postip_users'] = 'Поиск пользователей, создавших сообщения с этого IP-адреса';
$l['lookup'] = '[просмотреть]';
$l['member_online_today'] = '<strong>1</strong> участник сегодня был на форуме';
$l['members_were_online_today'] = ' Количество посетивших сегодня форум участников - <strong>{1} </strong>';
$l['member_online_hidden'] = ' ({1} пользователь был невидим)';
$l['members_online_hidden'] = ' ({1} пользователей было невидимо)';
$l['rating_thread'] = 'Оценивает тему';
$l['viewing_imcenter'] = 'Просматривает Центр IM';
$l['managing_favorites'] = 'Управляет Избранными темами';
$l['managing_subscriptions'] = 'Управляет подписками на темы';
$l['managing_group'] = 'Редактирует группу пользователей';
$l['viewing_modcp'] = 'Просматривает панель модератора';
$l['viewing_modlogs'] = 'Просматривает логи модератора';
$l['managing_announcements'] = 'Редактирует объявления';
$l['search_for_user'] = 'Использует поиск';
$l['managing_warninglogs'] = 'Редактирует логи предупреждений';
$l['searching_ips'] = 'Ищет по IP-адресу';
$l['viewing_reports'] = 'Просматривает жалобы на сообщения';
$l['adding_announcement'] = 'Добавляет объявление';
$l['deleting_announcement'] = 'Удаляет объявление';
$l['editing_announcement'] = 'Редактирует объявление';
$l['managing_modqueue'] = 'Редактирует очередь на модерацию';
$l['editing_user_profiles'] = 'Редактирует профиль пользователя';
$l['managing_bans'] = 'Редактирует список банов';
$l['revoking_warning'] = 'Отменяет предупреждение';
$l['warning_user'] = 'Предупреждает пользователя';
$l['viewing_warning'] = 'Просматривает предупреждения';
$l['managing_warnings'] = 'Редактирует предупреждения';
$l['changing_dst'] = 'Переключает настройки летнего времени';
$l['printing_thread'] = 'Печатает тему';
$l['printing_thread2'] = 'Печатает тему <a href="{1}">{2}</a>';
$l['managing_buddyignorelist'] = 'Редактирует список друзей и врагов';
