<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:15:48 +0000
// --------------------------------------------------------------------------------

$l['nav_portal'] = 'Портал';
$l['posted_by'] = 'Автор:';
$l['forum'] = 'Форум:';
$l['replies'] = 'Ответы';
$l['no_replies'] = 'Нет ответов';
$l['latest_threads'] = 'Последние темы';
$l['latest_threads_replies'] = 'Ответы:';
$l['latest_threads_views'] = 'Просмотры:';
$l['latest_threads_lastpost'] = 'Последнее сообщение:';
$l['private_messages'] = 'Личное сообщение';
$l['pms_received_new'] = '{1}, у вас есть <b>{2}</b> непрочитанное сообщение (й).';
$l['pms_unread'] = 'Непрочитанные сообщения';
$l['pms_total'] = 'Всего сообщений';
$l['search_forums'] = 'Поиск по форумам';
$l['advanced_search'] = 'Пробвинутый поиск';
$l['forum_stats'] = 'Статистика форума';
$l['num_members'] = 'Участники:';
$l['latest_member'] = 'Последний участник:';
$l['num_threads'] = 'Темы форума:';
$l['num_posts'] = 'Сообщения форумов:';
$l['full_stats'] = 'Полная статистика';
$l['welcome'] = 'Добро пожаловать, {1}';
$l['guest'] = 'Гость';
$l['guest_welcome_registration'] = 'You have to <a href="{1}">register</a> before you can post on our site.';
$l['username'] = 'Имя пользователя';
$l['password'] = 'Пароль';
$l['login'] = 'Войти!';
$l['member_welcome_lastvisit'] = 'Последнее посещение:';
$l['since_then'] = 'С тех пор прошло:';
$l['new_announcements'] = '{1} новых объявлений';
$l['new_announcement'] = '1 новое объявление';
$l['new_threads'] = '{1} новых тем';
$l['new_thread'] = '1 новая тема';
$l['new_posts'] = '{1} новых сообщений';
$l['new_post'] = '1 новое сообщение';
$l['view_new'] = 'Просмотр новых сообщений';
$l['view_todays'] = 'Просмотр сегодняшних сообщений';
$l['online'] = 'Пользователи в сети';
$l['online_user'] = 'Сейчас 1 пользователь в сети';
$l['online_users'] = 'Сейчас  <b>{1}</b> пользователей в сети.';
$l['online_counts'] = '<b>{1}</b> Участник(-ов) | <b>{2}</b> Гость(-ей)';
$l['print_this_item'] = 'Распечатать этот элемент ';
$l['send_to_friend'] = 'Отправить этот элемент другу';
$l['latest_announcements'] = 'Последние объявления';
$l['portal_disabled'] = 'Вы не можете использовать функции портала, так как он был отключен администратором.';
