<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:16:02 +0000
// --------------------------------------------------------------------------------

$l['redirect_threadrated'] = 'Спасибо, тема была оценена успешно. Теперь вы будете возвращены тему.';
$l['error_invalidrating'] = 'Вы выбрали неверный рейтинг для этой темы. Пожалуйста, вернитесь и попробуйте снова.';
$l['error_alreadyratedthread'] = 'Извините, но Вы уже голосовали за эту тему.';
$l['error_cannotrateownthread'] = 'К сожалению, вы не можете оценить свою собственную тему.';
$l['rating_votes_average'] = '{1} голос(ов) - {2} из 5 в среднем';
$l['one_star'] = '1 звезда из 5';
$l['two_stars'] = '2 звезды из 5';
$l['three_stars'] = '3 звезды из 5';
$l['four_stars'] = '4 звезды из 5';
$l['five_stars'] = '5 звезд из 5';
$l['rating_added'] = 'Ваша оценка была добавлена!';
