<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : Victor Efremov aka xtro
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Wed, 07 Dec 2016 08:15:33 +0000
// --------------------------------------------------------------------------------

$l['report_reason'] = 'Причина жалобы';
$l['report_to_mod'] = 'Жалоба модератору на контент';
$l['close_window'] = 'Закрыть окно';
$l['report_content'] = 'Содержание жалобы';
$l['report_reason_post'] = 'Жалоба на сообщение';
$l['report_reason_profile'] = 'Жалоба на профиль';
$l['report_reason_reputation'] = 'Жалоба на репутацию';
$l['report_reason_bad'] = 'Недопустимое содержимое';
$l['report_reason_spam'] = 'Спам';
$l['report_reason_rules'] = 'Нарушение правил форума';
$l['report_reason_wrong'] = 'Неправильный форум';
$l['report_reason_other'] = 'Другое';
$l['success_report_voted'] = 'Спасибо за жалобу на этот контент.<br />Администрация форума в ближайшее время проверит эту жалобу.';
$l['error_report_length'] = 'Просьба предоставить подробную причину вашей жалобы.';
$l['error_invalid_report'] = 'Этот контент либо не существует, либо на него нельзя подать жалобу.';
$l['error_report_duplicate'] = 'Это содержание уже сообщалось другим участником. <br /> Вы также можете сообщить об этом ниже контента.';
$l['report_reason_other_description'] = 'Если \'Другое\' просьба указать причину жалобы на этот контент.';
$l['error_invalid_report_reason'] = 'Неправильная причина.';
$l['error_comment_required'] = 'Для выбранной причины необходим дополнительный комментарий.';
