<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:16:20 +0000
// --------------------------------------------------------------------------------

$l['nav_sendthread'] = 'Отправить тему другу';
$l['send_thread'] = 'Отправить другу';
$l['recipient'] = 'Получатель:';
$l['recipient_note'] = 'Введите здесь email адрес друга';
$l['subject'] = 'Тема:';
$l['message'] = 'Сообщение:';
$l['error_nosubject'] = 'Вы должны ввести тему для сообщения, чтобы отправить вашу тему';
$l['error_nomessage'] = 'Вы должны ввести сообщение, прежде чем вы сможете отправить эту тему другу';
