<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:16:24 +0000
// --------------------------------------------------------------------------------

$l['nav_showteam'] = 'Команда форума';
$l['forum_team'] = 'Команда форума';
$l['moderators'] = 'Модераторы';
$l['username'] = 'Имя пользователя';
$l['lastvisit'] = 'Последний визит';
$l['email'] = 'Email';
$l['pm'] = 'ЛС';
$l['mod_forums'] = 'Форум(ы)';
$l['online'] = 'Онлайн';
$l['offline'] = 'Офлайн';
$l['away'] = 'Away';
$l['group_leaders'] = 'Лидер(ы)';
$l['group_members'] = 'Участник(и)';
$l['no_members'] = 'Нет участников в этой группе';
$l['error_noteamstoshow'] = 'Нет администрации форума для отображения';
