<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:16:33 +0000
// --------------------------------------------------------------------------------

$l['nav_stats'] = 'Статистика форумов';
$l['stats_disabled'] = 'Вы не можете просмотреть страницу статистики, т.к. она отключена администратором.';
$l['board_stats'] = 'Статистика форумов';
$l['none'] = 'Никого';
$l['totals'] = 'Всего';
$l['averages'] = 'В среднем';
$l['posts'] = 'Сообщений:';
$l['threads'] = 'Тем:';
$l['members'] = 'Участников:';
$l['ppd'] = 'Сообщений в день:';
$l['tpd'] = 'Тем в день:';
$l['mpd'] = 'Участников в день:';
$l['ppm'] = 'Сообщений на участника:';
$l['tpm'] = 'Тем на участника:';
$l['rpt'] = 'Ответов в тему:';
$l['no_posts'] = 'Нет';
$l['general'] = 'Главное';
$l['newest_member'] = 'Новый участник:';
$l['members_posted'] = 'Участники, которые размещали:';
$l['todays_top_poster'] = 'Сегодня самый активный: <b>{1}</b> (<b>{2}</b> сообщений)';
$l['popular_forum'] = 'Самый популярный форум: <b>{1}</b> (<b>{2}</b> сообщений, <b>{3}</b> тем)';
$l['most_popular'] = 'Самый популярный...';
$l['most_replied_threads'] = 'Больше всего ответов в теме:';
$l['most_viewed_threads'] = 'Самые популярные темы';
$l['not_enough_info_stats'] = 'К сожелению, недостаточно информации на форуме, чтобы сгенерировать статистику. До генерации статистики на форумах должен быть хотя бы один зарегистрировавшийся участник и одна созданная тема.';
$l['replies'] = 'ответов';
$l['views'] = 'просмотров';
$l['top_referrer'] = 'Топ ссылающихся: <strong>{1}</strong> (<strong>{2}</strong> рефералов)';
