<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:16:46 +0000
// --------------------------------------------------------------------------------

$l['ucp_nav_width'] = '180';
$l['ucp_nav_menu'] = 'Меню';
$l['ucp_nav_messenger'] = 'Переписка';
$l['ucp_nav_compose'] = 'Написать ЛС';
$l['ucp_nav_tracking'] = 'Отслеживание';
$l['ucp_nav_edit_folders'] = 'Редактировать папки';
$l['ucp_nav_profile'] = 'Ваш профиль';
$l['ucp_nav_edit_profile'] = 'Редактировать профиль';
$l['ucp_nav_edit_options'] = 'Редактировать параметры';
$l['ucp_nav_change_email'] = 'Изменить Email';
$l['ucp_nav_change_pass'] = 'Изменить пароль';
$l['ucp_nav_change_username'] = 'Изменить имя пользователя';
$l['ucp_nav_edit_sig'] = 'Изменить подпись';
$l['ucp_nav_change_avatar'] = 'Изменить аватар';
$l['ucp_nav_misc'] = 'Разное';
$l['ucp_nav_editlists'] = 'Друзья/Игнор список';
$l['ucp_nav_favorite_threads'] = 'Любимые темы';
$l['ucp_nav_subscribed_threads'] = 'Темы с подпиской';
$l['ucp_nav_forum_subscriptions'] = 'Форумы с подпиской';
$l['ucp_nav_drafts'] = 'Сохранить черновик';
$l['ucp_nav_drafts_active'] = '<strong>Черновик сохранён({1})</strong>';
$l['ucp_nav_notepad'] = 'Personal Pad';
$l['ucp_nav_view_profile'] = 'Просмотр профиля';
$l['ucp_nav_home'] = 'Панель управления пользователя';
$l['ucp_nav_usergroups'] = 'Членство в группах';
$l['ucp_nav_attachments'] = 'Управление вложениями';
