<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:16:56 +0000
// --------------------------------------------------------------------------------

$l['no_new_subject'] = 'Вы не введи новую тему';
$l['post_moderation'] = 'Ваш пост в настоящее время модерируется.';
$l['thread_moderation'] = 'Ваша тема в настоящее время модерируется.';
$l['post_doesnt_exist'] = 'Указанный пост не существует.';
$l['thread_doesnt_exist'] = 'Указанная тема не существует.';
$l['thread_closed_edit_subjects'] = 'Эта тема закрыта и вы не можете редактировать темы.';
$l['no_permission_edit_subject'] = 'У вас нет разрешения редактировать эту тему тему.';
$l['thread_closed_edit_message'] = 'Эта тема закрыта и вы не можете редактировать сообщения в ней.';
$l['no_permission_edit_post'] = 'У вас нет разрешения на редактирование этого сообщения.';
$l['edit_time_limit'] = 'Вы можете редактировать сообщения только в течение {1} минут после того, как оно было опубликовано.';
$l['postbit_edited'] = 'Это сообщение было отредактировано: {1}  ';
$l['postbit_editreason'] = 'Редактировать причину';
$l['save_changes'] = 'Сохранить изменения';
$l['cancel_edit'] = 'Отмена редактирования';
$l['answer_valid_not_exists'] = 'Вопрос, на который вы пытаетесь ответить не существует.';
$l['captcha_not_exists'] = 'Изображение для проверки (captcha), которое вы пытаетесь обновить, не существует.';
$l['captcha_valid_not_exists'] = 'Изображение для проверки (captcha) не существует.';
$l['captcha_does_not_match'] = 'Rод gроверки изображения , который вы ввели является неверным. Пожалуйста, введите код в точности так, как он появляется на картинке.';
$l['captcha_matches'] = 'Введенный вами код изображения был правильным.';
$l['answer_does_not_match'] = 'Ответ на этот вопрос вы ввели не правильно.';
$l['banned_username'] = 'Указанное имя пользователя было запрещено администратором';
$l['banned_characters_username'] = 'Ваше имя пользователя содержит один или несколько недопустимых символов';
$l['complex_password_fails'] = 'Пароль требует заглавные буквы, строчные буквы и цифры';
$l['username_taken'] = '{1} уже зарегистрирован другим участником';
$l['username_available'] = '{1} доступно';
$l['invalid_username'] = '{1} это не имя пользователя регистрируемого участника';
$l['valid_username'] = '{1} является действительным рефером.';
$l['buddylist_error'] = 'Похоже, что у вас нет приятелей в вашем списке друзей. Пожалуйста, добавьте некоторых, прежде чем пытаться использовать эту функцию.';
$l['close'] = 'Закрыть';
$l['select_buddies'] = 'Выбрать друга';
$l['select_buddies_desc'] = 'Чтобы добавить одного или несколько из ваших друзей в качестве получателей, выберите их ниже, и нажмите кнопку ОК.';
$l['selected_recipients'] = 'Выбранные получатели';
$l['ok'] = 'OK';
$l['cancel'] = 'Отмена';
$l['online'] = 'В сети';
$l['offline'] = 'Не в сети';
$l['edited_post'] = 'Сообщение отредактировано';
$l['usergroup'] = 'Группа пользователей';
