<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:19:48 +0000
// --------------------------------------------------------------------------------

$l['security_questions'] = 'Вопросы безопасности';
$l['security_questions_desc'] = 'Здесь вы можете создавать и управлять вопросами для безопасности, которые случайным образом будут показаны во время регистрации.';
$l['add_new_question'] = 'Добавить новый вопрос';
$l['add_new_question_desc'] = 'Добавить вопрос и его ответы на вопросы безопасности, которые будут использоваться во время регистрации.';
$l['edit_question'] = 'Редактировать Вопрос';
$l['edit_question_desc'] = 'Здесь вы должны изменить секретный вопрос.';
$l['options'] = 'Параметры';
$l['correct'] = 'Верный';
$l['incorrect'] = 'Неверный';
$l['disable_question'] = 'Отключить вопрос';
$l['enable_question'] = 'Включить вопрос';
$l['delete_question'] = 'Удалить вопрос';
$l['no_security_questions'] = 'Нет вопросов безопасности на вашем форуме сейчас.';
$l['question'] = 'Вопрос';
$l['question_desc'] = 'Введите вопрос, на который вы хотите чтобы ответили во время регистрации.';
$l['answers'] = 'Ответ(ы)';
$l['answers_desc'] = 'Введите ответ(ы) на поставленный выше вопрос. Пожалуйста, введите каждый ответ на отдельной строке.';
$l['active'] = 'Активный';
$l['save_question'] = 'Сохранить Вопрос';
$l['error_invalid_question'] = 'Вы выбрали неверный вопрос.';
$l['error_missing_question'] = 'Вы не ввели вопрос по этому вопросу';
$l['error_missing_answer'] = 'Вы не ввели никаких ответов на этот вопрос';
$l['success_question_created'] = 'Вопрос был успешно создан.';
$l['success_question_updated'] = 'Вопрос был успешно обновлен.';
$l['success_question_disabled'] = 'Вопрос был успешно отключен.';
$l['success_question_enabled'] = 'Вопрос был успешно включен.';
$l['success_question_deleted'] = 'Вопрос был успешно удален.';
$l['confirm_question_deletion'] = 'Вы уверены, что хотите удалить этот вопрос?';
