<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : Victor Efremov aka xtro
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Wed, 07 Dec 2016 09:02:26 +0000
// --------------------------------------------------------------------------------

$l['file_title'] = 'Менеджер файлов';
$l['file_nav_root'] = 'root';
$l['file_nav_edit'] = 'Редактировать файл: {1}';
$l['file_nav_delete_file'] = 'Удалить файл: {1}';
$l['file_nav_delete_dir'] = 'Удалить папку: {1}';
$l['file_nav_newdir'] = 'Новая папка';
$l['file_nav_newfile'] = 'Новый файл';
$l['file_sub_nfile'] = 'Новый файл';
$l['file_sub_ndir'] = 'Новая папка';
$l['file_sub_nfile_desc'] = 'Вы можете создать новый файл здесь';
$l['file_sub_ndir_desc'] = 'Вы можете создать новую папку здесь';
$l['file_file'] = 'Файл';
$l['file_actions'] = 'Действие';
$l['file_edit'] = 'Редактировать';
$l['file_edit_title'] = 'Редактировать файл: {1}/{2}';
$l['file_delete'] = 'Удалить';
$l['file_delete_file_title'] = 'Удалить файл: {1}/{2}';
$l['file_delete_file_desc'] = 'Вы уверены, что хотите удалить этот файл?';
$l['file_delete_dir_title'] = 'Удалить папку: {1}/';
$l['file_delete_dir_desc'] = 'Вы уверены, что хотите удалить эту папку и ее содержимое?';
$l['file_delete_warn'] = 'Это действие является необратимым, вы можете потерять важные файлы.';
$l['file_newdir_title'] = 'Создание папки в {1}/';
$l['file_newdir_desc'] = 'Имя папки';
$l['file_newdir_subdesc'] = 'Здесь вы можете указать имя новой папки.';
$l['file_newfile_title'] = 'Создание файла в {1}/';
$l['file_newfile_desc'] = 'Имя файла';
$l['file_newfile_subdesc'] = 'Здесь вы можете вставить имя и расширение нового файла';
$l['file_rename'] = 'Переименовать';
$l['file_button_save'] = 'Сохранить и закрыть';
$l['file_button_quick_save'] = 'Сохранить и продолжить';
$l['file_button_close'] = 'Закрыть';
$l['file_button_delete'] = 'Удалить';
$l['file_button_newdir'] = 'Создать папку';
$l['file_button_newfile'] = 'Создать файл';
$l['file_button_rename'] = 'Переименовать';
$l['file_button_cancel'] = 'Отмена';
$l['file_success_edit'] = 'Файл был успешно сохранен';
$l['file_success_delete_file'] = 'Файл был успешно удален';
$l['file_success_delete_dir'] = 'Папка была успешно удалена';
$l['file_success_newdir'] = 'Папка была успешно создана';
$l['file_success_newfile'] = 'Файл был успешно создан';
$l['file_error_exists'] = 'Выбранный файл не существует.';
$l['file_error_exists_dir'] = 'Выбранная папка не существует.';
$l['file_error_edit'] = 'К сожалению, что-то пошло не так при сохранении файла. Пожалуйста, попробуйте еще раз.';
$l['file_error_edit_file'] = 'Вы не выбрали файл для редактирования.';
$l['file_error_edit_type'] = 'Выбранный файл не может быть отредактирован.';
$l['file_error_delete'] = 'К сожалению, что-то пошло не так, пожалуйста, удалите файл/папку. Пожалуйста, попробуйте еще раз.';
$l['file_error_delete_root'] = 'Вы не можете удалять корень вашего форума.';
$l['file_error_delete_input'] = 'Вы не выбрали файл / папку для удаления.';
$l['file_error_newdir'] = 'К сожалению, что-то пошло не так во время создания папки. Пожалуйста, попробуйте еще раз.';
$l['file_error_newdir_exists'] = 'Папка с таким именем уже  существует .';
$l['file_error_newdir_name'] = 'Вы должны ввести имя папки.';
$l['file_error_newfile_exists'] = 'Файл с таким именем уже  существует .';
$l['file_error_newfile_name'] = 'Вы должны ввести имя файла.';
$l['file_error_rename'] = 'К сожалению, что-то пошло не так во время переименования файла / папки. Пожалуйста, попробуйте еще раз.';
$l['file_success_rename'] = 'Файл был переименован успешно';
$l['file_success_rename_dir'] = 'Папка была переименована успешно';
$l['file_error_rename_exists'] = 'Уже существует файл или папка с новым вставляемым именем.';
$l['file_error_rename_not_exists'] = 'Выбранный файл / папка не существует.';
$l['file_error_rename_name'] = 'Вам необходимо ввести новое имя.';
$l['file_error_rename_input'] = 'Вы не выбрали файл / папку, которую необходимо переименовать.';
