<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:20:28 +0000
// --------------------------------------------------------------------------------

$l['moderation_queue'] = 'Очередь Модерации';
$l['threads'] = 'Темы';
$l['threads_desc'] = 'Здесь Вы можете просмотреть и одобрить темы, ожидающих одобрения.';
$l['posts'] = 'Сообщения';
$l['posts_desc'] = 'Здесь Вы можете просмотреть и утвердить сообзщения в очереди модерации.';
$l['attachments'] = 'Вложения';
$l['attachments_desc'] = 'Здесь Вы можете просмотреть и одобрить вложения в очереди модерации.';
$l['threads_awaiting_moderation'] = 'Темы, ожидающие модерации';
$l['posts_awaiting_moderation'] = 'Сообщения, ожидающие модерации';
$l['attachments_awaiting_moderation'] = 'Вложения, ожидающие модерации';
$l['error_no_posts'] = 'В настоящее время нет сообщений, ожидающих модерации';
$l['error_no_attachments'] = 'В настоящее время нет вложений, ожидающих модерации';
$l['error_no_threads'] = 'Нет ни одной темы, сообщения или вложения в настоящее время ожидающих модерации.';
$l['success_threads'] = 'Выбранные темы были успешно премодерированы.';
$l['success_posts'] = 'Выбранные сообщения были успешно премодерированы.';
$l['success_attachments'] = 'Выбранные вложения были успешно премодерированы.';
$l['subject'] = 'Тема';
$l['author'] = 'Автор';
$l['posted'] = 'Опубликовано';
$l['ignore'] = 'Игнор';
$l['approve'] = 'Одобрить';
$l['forum'] = 'Форум:';
$l['thread'] = 'Тема:';
$l['post'] = 'Сообщение:';
$l['re'] = 'RE:';
$l['filename'] = 'Имя файла';
$l['uploadedby'] = 'Загрузил';
$l['controls'] = 'Управление';
$l['mark_as_ignored'] = 'Отметить все как игнорируемые';
$l['mark_as_deleted'] = 'Отметить все для удаления';
$l['mark_as_approved'] = 'Отметить все как одобренные';
$l['perform_action'] = 'Выполните действия';
