<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:20:32 +0000
// --------------------------------------------------------------------------------

$l['forums_and_posts'] = 'Форумы &amp; Сообщения';
$l['forum_management'] = 'Управление форумом';
$l['forum_announcements'] = 'Объявления форума';
$l['moderation_queue'] = 'Очередь модерации';
$l['attachments'] = 'Вложения';
$l['can_manage_forums'] = 'Можно управлять форумами?';
$l['can_manage_forum_announcements'] = 'Можно управлять объявлениями форума?';
$l['can_moderate'] = 'Можно модерировать сообщения, темы и вложения?';
$l['can_manage_attachments'] = 'Можно модерировать вложения?';
