<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:20:42 +0000
// --------------------------------------------------------------------------------

$l['hello_desc'] = 'Образец плагина, который позволяет создавать сообщения на главной странице и добавить их к каждому сообщению.';
$l['setting_group_hello'] = 'Hello World!';
$l['setting_group_hello_desc'] = 'параметры плагина Hello World!.';
$l['setting_hello_display1'] = 'Отображение сообщений на главной';
$l['setting_hello_display1_desc'] = 'Установите нет, если вы не хотите отображать сообщения на главной.';
$l['setting_hello_display2'] = 'Отображение сообщений Postbit';
$l['setting_hello_display2_desc'] = 'Установите в нет, если вы не хотите, чтобы отобразить сообщения ниже каждого сообщения.';
$l['hello_uninstall'] = 'Hello World! удаление';
$l['hello_uninstall_message'] = 'Вы хотите, чтобы удалить все сообщения из базы данных?';
