<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:20:59 +0000
// --------------------------------------------------------------------------------

$l['preferences_and_personal_notes'] = 'Предпочтения &amp; Персональные заметки';
$l['prefs_and_personal_notes_description'] = 'Здесь вы можете управялть предпочтениями своей контрольной панели и оставить личные заметки для себя.';
$l['preferences'] = 'Предпочтения';
$l['global_preferences'] = 'Глобальные Предпочтения';
$l['acp_theme'] = 'Тема контрольной панели администратора';
$l['select_acp_theme'] = 'Пожалуйста, выберите для использования тему панели управления администратора.';
$l['acp_language'] = 'Язык панели управления администратора';
$l['select_acp_language'] = 'Пожалуйста, выберите язык панели управления администратора';
$l['notes_not_shared'] = 'Эти заметки не используются совместно с другими администраторами.';
$l['save_notes_and_prefs'] = 'Сохранить персональные заметки & предпочтения';
$l['personal_notes'] = 'Персональные заметки';
$l['codemirror'] = 'Вкл / выкл Code Mirror';
$l['use_codemirror_desc'] = 'Это предпочтение позволяет отключить Code Mirror (используется при редактировании шаблона и редактирования таблиц стилей для подсветки синтаксиса), если вы испытываете проблемы / медленная загрузка.';
$l['success_preferences_updated'] = 'Предпочтения были успешно обновлены.';
$l['use_2fa_desc'] = 'Двухфакторная аутентификация представляет собой способ защититы вашего аккаунта администратора. После того, как вы включили его вы увидите QR-код, ниже которого вам нужно сканировать при помощи приложения <a href="http://docs.mybb.com/1.8/administration/security/2fa/" target="_blank">типа Google Authenticator или Authy</a>. Эти приложения будут генерировать маркер, который вам нужно ввести на каждом входе в панель управления .';
$l['my2fa_qr'] = 'Код двухфакторной аутентификации';
$l['recovery_codes_desc'] = 'Просмотреть ваш <a href="index.php?module=home-preferences&amp;action=recovery_codes">код восстановления</a>.';
$l['recovery_codes'] = 'Коды восстановления';
$l['recovery_codes_warning'] = '<b>Примечание:</b> коды будут использованы при каждом посещении страницы и могут быть использованы только один раз.';
