<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:20:47 +0000
// --------------------------------------------------------------------------------

$l['mybb_credits'] = 'MyBB уважение';
$l['mybb_credits_description'] = 'Эти люди внесли свое время и усилия для создания MyBB.';
$l['about_the_team'] = 'О команде';
$l['check_for_updates'] = 'Проверьте обновления';
$l['error_communication'] = 'Существовала проблема загрузки последних благодарностей. Пожалуйста, повторите попытку через несколько минут.';
$l['no_credits'] = 'Нет сохранённых благодарностей <a href="index.php?module=home-credits&amp;fetch_new=1">Проверьте Обновление</a>.';
$l['success_credits_updated'] = 'Кэш MyBB уважений был успешно обновлен.';
