<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:20:55 +0000
// --------------------------------------------------------------------------------

$l['home'] = 'Начало';
$l['dashboard'] = 'Рабочий стол';
$l['preferences'] = 'Предпочтения';
$l['mybb_credits'] = 'MyBB уважение';
$l['add_new_forum'] = 'Добавить новый форум';
$l['search_for_users'] = 'Поиск пользователей';
$l['themes'] = 'Темы';
$l['templates'] = 'Шаблоны';
$l['plugins'] = 'Плагины';
$l['database_backups'] = 'Бэкапы БД';
$l['quick_access'] = 'Быстрый доступ';
$l['online_admins'] = 'Администраторы онлайн';
$l['ipaddress'] = 'IP адрес:';
$l['mybb_documentation'] = 'MyBB документация';
