<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:21:03 +0000
// --------------------------------------------------------------------------------

$l['templates_and_style'] = 'Шаблоны &amp; Стиль';
$l['themes'] = 'Темы';
$l['templates'] = 'Шаблоны';
$l['can_manage_themes'] = 'Можно управлять темами?';
$l['can_manage_templates'] = 'Можно управлять шаблонами?';
