<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:23:20 +0000
// --------------------------------------------------------------------------------

$l['optimize_database'] = 'Оптимизация БД';
$l['table_selection'] = 'Выбранные таблицы';
$l['tables_select_desc'] = 'Вы можете выбрать таблицы базы данных, для которых вы хотите выполнить это действие. Удерживайте нажатой клавишу CTRL, чтобы выбрать несколько таблиц.';
$l['select_all'] = 'Выбрать ВСЕ';
$l['deselect_all'] = 'Отменить ВСЕ';
$l['select_forum_tables'] = 'Выбрать таблицы форума';
$l['optimize_selected_tables'] = 'Оптимизация выбранных таблиц';
$l['error_no_tables_selected'] = 'Вы не выбрали ни одной таблицы базы данных для оптимизации .';
$l['success_tables_optimized'] = 'Выбранные таблицы были оптимизированы и проанализированы успешно.';
