<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:23:32 +0000
// --------------------------------------------------------------------------------

$l['spam_logs'] = 'Журналы спама';
$l['spam_logs_desc'] = 'Этот раздел позволяет просматривать историю пользователей, заблокированных спам-фильтром.';
$l['prune_spam_logs'] = 'Очистка журнала спама';
$l['prune_spam_logs_desc'] = 'Здесь вы можете сократить журнал спама в соответствии с указанными критериями.';
$l['spam_username'] = 'Имя пользователя';
$l['spam_email'] = 'Email адрес';
$l['spam_ip'] = 'IP адрес';
$l['spam_date'] = 'Дата';
$l['spam_confidence'] = 'Доверительный';
$l['no_spam_logs'] = 'Нет пользователей, которые были заблокированы спам-фильтром .';
$l['success_pruned_spam_logs'] = 'Журнал спама был успешно очищен.';
$l['note_logs_locked'] = 'По соображениям безопасности, зарегистрированные менее 24 часов назад не могут быть очищены.';
$l['all_usernames'] = 'Все имена пользователей';
$l['all_emails'] = ' Все Email адреса';
$l['date_range'] = 'Диапозон дат:';
$l['days'] = 'дней';
$l['filter_spam_logs'] = 'Фильтр журнала спама';
$l['asc'] = 'возрастанию';
$l['desc'] = 'убыванию';
$l['in'] = 'по';
$l['order'] = ' ';
$l['sort_by'] = 'Сортировать по ';
$l['results_per_page'] = ' результатов на странице';
