<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:22:58 +0000
// --------------------------------------------------------------------------------

$l['file_verification'] = ' Проверка файлов';
$l['checking'] = 'Проверяется...';
$l['file_verification_message'] = 'Этот процесс будет проверять все файлы MyBB по умолчанию для проверки достоверности. Нажмите Да, чтобы продолжить.<br /> <small>Обратите внимание, что этот процесс не может различать пользовательских модификаций и фактической коррупции в файлах. Поэтому вы должны принять с осторожность восстановление файлов, а этот процесс возвращается как "коррумпированный".</small>';
$l['error_communication'] = 'Существует проблема обмена с MyBB сервером. Пожалуйста, повторите попытку через несколько минут.';
$l['file'] = 'Файл';
$l['no_corrupt_files_found'] = 'Поздравления! Поврежденных файлов в вашей установке найдено  не было.';
$l['found_problems'] = 'Найденные проблемы';
$l['no_problems_found'] = 'Проблем не обнаружено';
$l['changed'] = 'Изменён';
$l['missing'] = 'Отсутствует';
$l['status'] = 'Статус';
