<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:22:54 +0000
// --------------------------------------------------------------------------------

$l['cache'] = 'Кэш:';
$l['cache_manager'] = 'Управление кэшем';
$l['cache_manager_description'] = 'Здесь вы можете управлять кэшем, который используются в качестве метода оптимизации MyBB. Перепостроение кэша будет принимать все необходимые данные, используемые для создания кэш-памяти и выполнит повторную синхронизацию. Перезагрузка кэша повторно загрузит его в выбранный обработчик кэша (disk, eaccelerator, memcache, и т.п.). Перезагрузка полезна при переключении  из базы данных или файловой системы в xcache, eaccelerator или другой обработчик кэша.';
$l['rebuild_cache'] = 'Перестроить кэш';
$l['reload_cache'] = 'Перегрузить кэш';
$l['rebuild_reload_all'] = '(Перестроить & Перегрузить Всё)';
$l['error_cannot_rebuild'] = 'Кэш перестроить невозможно.';
$l['error_empty_cache'] = 'Кэш пуст.';
$l['error_incorrect_cache'] = 'Некорректное указание кэша .';
$l['error_no_cache_specified'] = 'Вы не указали кэш для отображения.';
$l['success_cache_rebuilt'] = 'Кэш был перестроен успешно.';
$l['success_cache_reloaded'] = 'Кэш был перегружен успешно.';
