<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:23:36 +0000
// --------------------------------------------------------------------------------

$l['statistics'] = 'Статистика';
$l['overall_statistics'] = 'Сводная статистика';
$l['overall_statistics_desc'] = 'Здесь вы можете просматривать общую статистику на вашем форуме. Часовой пояс в формате UTC.';
$l['date_range'] = 'Диапазон дат';
$l['date'] = 'Дата';
$l['users'] = 'Пользователи';
$l['threads'] = 'Темы';
$l['posts'] = 'Сообщения';
$l['from'] = 'Из';
$l['to'] = 'для';
$l['increase'] = 'Увеличение';
$l['no_change'] = 'Без изменений';
$l['decrease'] = 'Уменьшение';
$l['error_no_results_found_for_criteria'] = 'Мы не смогли найти каких-либо результатов за указанный диапазон дат, который вы указали. Пожалуйста, попробуйте другой диапазон дат.';
$l['error_no_statistics_available_yet'] = 'К сожалению, нет в настоящее время пока нет статистических данных, доступных для вашего форума.';
