<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:23:16 +0000
// --------------------------------------------------------------------------------

$l['tools_and_maintenance'] = 'Инструменты &amp; Обслуживание';
$l['maintenance'] = 'Обслуживание';
$l['logs'] = 'Логи';
$l['system_health'] = 'Работоспособность системы';
$l['cache_manager'] = 'Управление кэшем';
$l['task_manager'] = 'Управление задачами';
$l['recount_and_rebuild'] = 'Пересчет &amp; Перестроение';
$l['view_php_info'] = 'Просмотр инфо о PHP';
$l['database_backups'] = 'Бэкапы БД';
$l['optimize_database'] = 'Оптимизация БД';
$l['file_verification'] = 'Проверка файлов';
$l['administrator_log'] = 'Лог администратора';
$l['moderator_log'] = 'Лог модератора';
$l['user_email_log'] = 'Лог почты пользователя';
$l['system_mail_log'] = 'Лог системного журнала электронной почты';
$l['user_warning_log'] = 'Лог предупреждений пользователя';
$l['spam_log'] = 'Лог спама';
$l['statistics'] = 'Статистика';
$l['can_access_system_health'] = 'Можно иметь доступ к работоспособности ситемы?';
$l['can_manage_cache'] = 'Можно управлять кэшем?';
$l['can_manage_tasks'] = 'Можно управлять запланированными задачами?';
$l['can_manage_db_backup'] = 'Можно управлять бэкапами БД?';
$l['can_optimize_db'] = 'Можно оптимизироваь БД?';
$l['can_recount_and_rebuild'] = 'Можно пересчитать и восстановить?';
$l['can_manage_admin_logs'] = 'Можно управлять логом администратора?';
$l['can_manage_mod_logs'] = 'Можно управлять логом модератора?';
$l['can_manage_user_mail_log'] = 'Можно управлять логом почты пользователя?';
$l['can_manage_system_mail_log'] = 'Можно управлять системным логом почты?';
$l['can_manage_user_warning_log'] = 'Можно управлять логом предупреждений пользователя?';
$l['can_manage_spam_log'] = 'Можно управлять логом спама?';
$l['can_view_php_info'] = 'Можно просматривать информацию о PHP?';
$l['can_manage_file_verification'] = 'Можно управлять проверкой файла?';
$l['can_view_statistics'] = 'Можно просматривать статистику?';
