<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:24:03 +0000
// --------------------------------------------------------------------------------

$l['banning'] = 'Баны';
$l['banned_accounts'] = 'Забаненные акаунты';
$l['banned_accounts_desc'] = 'Здесь Вы можете управлять учетными записями пользователей, которым вы запретили доступ к форумам.';
$l['ban_a_user'] = 'Забанить пользователя';
$l['ban_a_user_desc'] = 'Здесь вы можете банить пользователей.';
$l['edit_ban'] = 'Редактировать бан';
$l['edit_ban_desc'] = 'Здесь вы можете редактировать причину и продолжительность запрещенных в настоящий момент пользователей.';
$l['banned_ips'] = 'Забаненные IP';
$l['disallowed_usernames'] = 'Запрещённые имена пользователя';
$l['disallowed_email_addresses'] = 'Запрещнные Email адреса';
$l['error_invalid_ban'] = 'Вы выбрали неверный бан для редактирования.';
$l['error_invalid_username'] = 'Введённое имя пользователя недействительно или не существует.';
$l['error_no_perm_to_ban'] = 'У вас нет разрешения банить этого пользователя.';
$l['error_already_banned'] = 'Этот пользователь уже принадлежит к запрещенной группе и не может быть добавлен снова.';
$l['error_ban_self'] = 'Вы не можете запретить себя.';
$l['error_no_reason'] = 'Вы не ввели причину бана этого пользователя.';
$l['success_ban_lifted'] = 'Выбранный бан был успешно снят.';
$l['success_banned'] = 'Выбранный пользователь был успешно забанен.';
$l['success_ban_updated'] = 'Выбранный бан был успешно обновлен.';
$l['success_pruned'] = 'Выбранные сообщения и темы пользователя были успешно очищены.';
$l['confirm_lift_ban'] = 'Вы уверены, что хотите снять этот бан?';
$l['confirm_prune'] = 'Вы уверены, что вы хотите очистить все темы и сообщения, созданные этим пользователем?';
$l['ban_username'] = 'Имя пользовтаеля <em>*</em>';
$l['autocomplete_enabled'] = 'В этом поле включено автозаполнение.';
$l['ban_reason'] = 'Причина бана';
$l['ban_group'] = 'Группа забаненных <em>*</em>';
$l['ban_group_desc'] = 'Для того, чтобы забанить этого пользователя его необходимо переместиь в группу забаненныз.';
$l['ban_time'] = 'Продолжительность запрета <em>*</em>';
$l['user'] = 'Пользователь';
$l['moderation'] = 'Модерация';
$l['ban_lifts_on'] = 'Бан поднят';
$l['time_left'] = 'Оставшееся время';
$l['permenantly'] = 'постоянно';
$l['na'] = 'Н/Д';
$l['for'] = 'на';
$l['bannedby_x_on_x'] = '<strong>{1}</strong><br /><small>Забанил {2} - {3} {4}</small>';
$l['lift'] = 'снять бан';
$l['no_banned_users'] = 'В настоящий момент у вас нет запрещённых пользователей';
$l['prune_threads_and_posts'] = 'Очистить Темы &amp; Сообщения';
$l['ban_user'] = 'Забанить пользователя';
$l['update_ban'] = 'Обновить бан';
