<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: http://www.mybb.com
 * License: http://www.mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : Russian
// Author of the language pack : RUNetCMS Group
// Language pack translators website : http://runetcms.ru/
// Compatible version of MyBB : 1807
// Last edited in MyBB Editor by : XTRO
// Last edited date : Thu, 09 Jun 2016 13:24:21 +0000
// --------------------------------------------------------------------------------

$l['users_and_groups'] = 'Пользователи &amp; Группы';
$l['users'] = 'Пользователи';
$l['groups'] = 'Группы';
$l['user_titles'] = 'Звания пользователей';
$l['banning'] = 'Блокирование';
$l['admin_permissions'] = 'Права доступа администратора';
$l['mass_mail'] = 'Массовая рассылка';
$l['group_promotions'] = 'Поощрение групп';
$l['can_manage_users'] = 'Может управлять пользователями?';
$l['can_manage_user_groups'] = 'Может управлять группами пользователей?';
$l['can_manage_user_titles'] = 'Может управлять званиями пользователей?';
$l['can_manage_user_bans'] = 'Может управлять банами пользователей?';
$l['can_manage_admin_permissions'] = 'Может управлять разрешениями?';
$l['can_send_mass_mail'] = 'Может управлять массовой рассылкой?';
$l['can_manage_group_promotions'] = 'Может управлять акциями групп?';
